/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodayRouteImport } from './routes/today'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PairedRouteImport } from './routes/paired'
import { Route as OnboardRouteImport } from './routes/onboard'
import { Route as MomentsRouteImport } from './routes/moments'
import { Route as MapRouteImport } from './routes/map'
import { Route as JoinSpaceRouteImport } from './routes/join-space'
import { Route as CreateSpaceRouteImport } from './routes/create-space'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'

const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PairedRoute = PairedRouteImport.update({
  id: '/paired',
  path: '/paired',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardRoute = OnboardRouteImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MomentsRoute = MomentsRouteImport.update({
  id: '/moments',
  path: '/moments',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinSpaceRoute = JoinSpaceRouteImport.update({
  id: '/join-space',
  path: '/join-space',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateSpaceRoute = CreateSpaceRouteImport.update({
  id: '/create-space',
  path: '/create-space',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/create-space': typeof CreateSpaceRoute
  '/join-space': typeof JoinSpaceRoute
  '/map': typeof MapRoute
  '/moments': typeof MomentsRoute
  '/onboard': typeof OnboardRoute
  '/paired': typeof PairedRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/today': typeof TodayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/create-space': typeof CreateSpaceRoute
  '/join-space': typeof JoinSpaceRoute
  '/map': typeof MapRoute
  '/moments': typeof MomentsRoute
  '/onboard': typeof OnboardRoute
  '/paired': typeof PairedRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/today': typeof TodayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/create-space': typeof CreateSpaceRoute
  '/join-space': typeof JoinSpaceRoute
  '/map': typeof MapRoute
  '/moments': typeof MomentsRoute
  '/onboard': typeof OnboardRoute
  '/paired': typeof PairedRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/today': typeof TodayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/create-space'
    | '/join-space'
    | '/map'
    | '/moments'
    | '/onboard'
    | '/paired'
    | '/privacy'
    | '/settings'
    | '/today'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/create-space'
    | '/join-space'
    | '/map'
    | '/moments'
    | '/onboard'
    | '/paired'
    | '/privacy'
    | '/settings'
    | '/today'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/create-space'
    | '/join-space'
    | '/map'
    | '/moments'
    | '/onboard'
    | '/paired'
    | '/privacy'
    | '/settings'
    | '/today'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CreateSpaceRoute: typeof CreateSpaceRoute
  JoinSpaceRoute: typeof JoinSpaceRoute
  MapRoute: typeof MapRoute
  MomentsRoute: typeof MomentsRoute
  OnboardRoute: typeof OnboardRoute
  PairedRoute: typeof PairedRoute
  PrivacyRoute: typeof PrivacyRoute
  SettingsRoute: typeof SettingsRoute
  TodayRoute: typeof TodayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paired': {
      id: '/paired'
      path: '/paired'
      fullPath: '/paired'
      preLoaderRoute: typeof PairedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboard': {
      id: '/onboard'
      path: '/onboard'
      fullPath: '/onboard'
      preLoaderRoute: typeof OnboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moments': {
      id: '/moments'
      path: '/moments'
      fullPath: '/moments'
      preLoaderRoute: typeof MomentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join-space': {
      id: '/join-space'
      path: '/join-space'
      fullPath: '/join-space'
      preLoaderRoute: typeof JoinSpaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-space': {
      id: '/create-space'
      path: '/create-space'
      fullPath: '/create-space'
      preLoaderRoute: typeof CreateSpaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CreateSpaceRoute: CreateSpaceRoute,
  JoinSpaceRoute: JoinSpaceRoute,
  MapRoute: MapRoute,
  MomentsRoute: MomentsRoute,
  OnboardRoute: OnboardRoute,
  PairedRoute: PairedRoute,
  PrivacyRoute: PrivacyRoute,
  SettingsRoute: SettingsRoute,
  TodayRoute: TodayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
